[package]
name = "io_tee"
description = "Tee Read, BufRead, and Seek instances to a writer"
repository = "https://github.com/TheOnlyMrCat/io_tee"
readme = "README.md"
license = "MIT OR Apache-2.0"
version = "0.1.1"
edition = "2018"

[dependencies]
